name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 11']
        swift-version: [5.1]

    steps:
    - uses: actions/checkout@v1
    - name: Install Carthage
      run: brew install carthage
    - name: Install Dependency
      run: carthage update --new-resolver --platform iOS --no-use-binaries --cache-builds
    - name: Build
      run: xcodebuild -project XYEureka.xcodeproj -scheme XYEureka -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
