name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 11']
        swift-version: [5.1]

    steps:
    - uses: actions/checkout@v1
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    - name: Pod Install
      run: pod install
    - name: Build
      run: xcodebuild -workspace XYEureka.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
